# config/prompts.yml
generate_backstory:
  template: "Créez une histoire pour un personnage ayant les attributs suivants : Nom : %{name}, Race: %{race}, Classe du perso: %{univers_class}. L'histoire doit être intéressante et s'inscrire dans l'univers de %{universe}."
