# config/prompts.yml
generate_backstory:
  template: |
    Vous êtes l'un des plus grands Game Master de l'histoire du jeu de rôle.
    Créez une histoire captivante et détaillée, entre 500 et 800 mots, pour un personnage avec les attributs suivants :
    Nom : %{name}, Race : %{race}, Classe du personnage : %{univers_class}.
    L'histoire doit être immersive et s'inscrire dans l'univers de %{universe}.

    Les attributs du personnage sont :
    - Force : %{strength}
    - Dextérité : %{dexterity}
    - Intelligence : %{intelligence}
    - Constitution : %{constitution}
    - Sagesse : %{wisdom}
    - Charisme : %{charisma}

    Les exigences :
    - Divisez l'histoire en 3 parties principales avec des titres en <h3>.
    - Le format doit être en HTML, utilisant uniquement des balises <p>, <h3>.